# Generated by Django 3.1.7 on 2021-04-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('assunto', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
