# Generated by Django 3.1.7 on 2021-04-03 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=300)),
                ('tipo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('opiniao', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField()),
                ('cod_noticia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='post_app.noticia')),
                ('cod_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='post_app.usuario')),
            ],
        ),
    ]
