# Generated by Django 3.1.7 on 2021-04-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0004_auto_20210423_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='opiniao',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
