# Generated by Django 3.1.7 on 2021-04-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0006_auto_20210423_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
